### ISSUE TITLE
OCTG app

### ISSUE THREAD

**Issue by lordlumley** [lordlumley/stringnosis.com#1]
A link needs to be designed and added for exposure of our OCTG app

**Comment by ashhorsman** [comment]
There are links in the two images for Google and Apple. 

Are you lookin for a more obvious, to download this app click here or something?

**Comment by lordlumley** [comment]
Good work to date but we need to jazz it up a little. Leaving issue open.

**Comment by lordlumley** [comment]
- Remove border radius
Sawp text and image
Title to left
Add more info to title - powerful strength calculator in your pocket
